import React, { useState } from 'react';
import { Zap, Pencil, Play, RefreshCw, CheckCircle2, AlertCircle, Repeat, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useData } from '../../lib/api';
import { Loading, ErrorState } from '../Common';
import { WorkspaceHead, WorkspaceModal, Action, DeleteAction, FormField, Submit, EmptyWorkspace, useMutation } from './WorkspaceUI';
const triggers = { task_created: 'Task dibuat', status_changed: 'Status berubah' };
const actions = { set_status: 'Ubah status', set_priority: 'Ubah prioritas', assign: 'Tambahkan PIC', add_tag: 'Tambahkan tag', notify: 'Kirim notifikasi' };
const keys = ['name', 'trigger', 'condition_field', 'condition_value', 'action', 'action_value', 'enabled'];
const payload = r => Object.fromEntries(keys.map(k => [k, r[k]]));
export const AutomationsPage = ({ p, meta, statuses, manager }) => {
  const base = `/projects/${p.id}/workspace`, info = useData(`${base}/automations`);
  const [editing, setEditing] = useState(null); const { run, busy } = useMutation(info.reload);
  const people = meta.people.filter(m => m.role !== 'Client'); const priorities = ['Mendesak', 'Tinggi', 'Sedang', 'Rendah'];
  const valueLabel = r => ['assign', 'notify'].includes(r.action) ? meta.people.find(m => m.id === r.action_value)?.name || 'Anggota tidak aktif' : r.action_value;
  if (info.loading && !info.data) return <Loading />; if (info.error) return <ErrorState error={info.error} reload={info.reload} />;
  const data = info.data;
  return <div data-testid="automations-page"><WorkspaceHead id="automations" title="Automasi" subtitle={`${data.rules.filter(r => r.enabled).length} aturan aktif`}><Action id="automations-refresh" secondary icon={RefreshCw} onClick={info.reload}>Muat ulang</Action>{manager && <Action id="create-automation" icon={Zap} onClick={() => setEditing({ name: '', trigger: 'task_created', condition_field: '', condition_value: '', action: 'set_priority', action_value: 'Tinggi', enabled: true })}>Aturan baru</Action>}</WorkspaceHead>
    {!data.rules.length && <EmptyWorkspace title="Belum ada aturan automasi" id="automations-empty" />}<div className="pw-rule-list">{data.rules.map(r => <article className="pw-rule" key={r.id} data-testid={`automation-rule-${r.id}`}><div className={`pw-rule-icon ${r.enabled ? 'active' : ''}`}><Zap size={20} /></div><div className="pw-rule-info"><b data-testid={`rule-name-${r.id}`}>{r.name}</b><div><span>{triggers[r.trigger]}{r.condition_field && ` · ${r.condition_value}`}</span><ArrowRight size={14} /><span>{actions[r.action]}: {valueLabel(r)}</span></div></div>{manager && <div className="pw-actions"><label className="pw-switch"><input type="checkbox" data-testid={`toggle-rule-${r.id}`} checked={r.enabled} disabled={busy} onChange={e => run('patch', `${base}/automations/${r.id}`, { ...payload(r), enabled: e.target.checked })} /><span /></label><button className="pw-icon" data-testid={`edit-rule-${r.id}`} title="Edit aturan" onClick={() => setEditing(r)}><Pencil size={15} /></button><DeleteAction id={`delete-rule-${r.id}`} onClick={() => window.confirm('Hapus aturan ini?') && run('delete', `${base}/automations/${r.id}`)} /></div>}</article>)}</div>
    <section className="pw-section"><WorkspaceHead id="scheduled" title="Tugas berulang & pengingat" subtitle="Pemeriksaan setiap 15 menit">{manager && <Action id="run-due-now" secondary icon={Play} busy={busy} onClick={() => run('post', `${base}/run-due`, {}, 'Pemeriksaan jadwal dimulai')}>Periksa sekarang</Action>}</WorkspaceHead>{data.last_run && <p className="pw-muted" data-testid="last-schedule-run">Pemeriksaan terakhir: {new Date(data.last_run.finished_at).toLocaleString('id-ID')} · {data.last_run.created || 0} task dibuat · {data.last_run.reminded || 0} pengingat</p>}
      <div className="pw-config-list">{data.schedules.map(s => <div className="pw-config-row" key={s.id} data-testid={`scheduled-task-${s.id}`}><Repeat size={18} /><span><Link data-testid={`schedule-open-task-${s.id}`} to={`/projects/${p.id}/kanban?task=${s.task_id}`}><b>{s.task_title}</b></Link><small>{({ daily: 'Harian', weekly: 'Mingguan', monthly: 'Bulanan' })[s.frequency]} · {s.enabled ? new Date(s.next_run).toLocaleString('id-ID') : 'Dijeda'}{s.error && ` · ${s.error}`}</small></span>{manager && <label className="pw-switch"><input type="checkbox" data-testid={`schedule-toggle-${s.id}`} checked={s.enabled} disabled={busy} onChange={e => run('post', `${base}/tasks/${s.task_id}/schedule`, { frequency: s.frequency, next_run: s.next_run, end_at: s.end_at, enabled: e.target.checked })} /><span /></label>}</div>)}{!data.schedules.length && <p className="pw-muted" data-testid="schedules-empty">Belum ada tugas berulang.</p>}</div>
    </section><section className="pw-section"><WorkspaceHead id="automation-log" title="Riwayat automasi" /><div className="pw-event-log">{data.logs.map(l => <div key={l.id} data-testid={`automation-log-${l.id}`}>{l.status === 'success' ? <CheckCircle2 size={17} className="pw-success" /> : <AlertCircle size={17} className="pw-danger" />}<span><b>{l.rule_name}</b><small>{l.task_title}{l.message && ` · ${l.message}`}</small></span><time>{new Date(l.created_at).toLocaleString('id-ID')}</time></div>)}{!data.logs.length && <p className="pw-muted" data-testid="automation-log-empty">Belum ada aturan yang dijalankan.</p>}</div></section>
    <WorkspaceModal id="automation-form" open={!!editing} onClose={() => setEditing(null)} title={editing?.id ? 'Edit aturan' : 'Aturan automasi baru'}>{editing && <form className="pw-form" onSubmit={async e => { e.preventDefault(); if (await run(editing.id ? 'patch' : 'post', `${base}/automations${editing.id ? '/' + editing.id : ''}`, payload(editing))) setEditing(null); }}><FormField id="automation-name" label="Nama aturan" required maxLength={120} value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} /><FormField id="automation-trigger" label="Ketika" as="select" value={editing.trigger} onChange={e => setEditing({ ...editing, trigger: e.target.value })}>{Object.entries(triggers).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</FormField><div className="pw-form-grid"><FormField id="automation-condition" label="Dengan kondisi" as="select" value={editing.condition_field} onChange={e => setEditing({ ...editing, condition_field: e.target.value, condition_value: e.target.value === 'status' ? statuses[0]?.name : e.target.value === 'priority' ? 'Tinggi' : '' })}><option value="">Semua task</option><option value="status">Status</option><option value="priority">Prioritas</option></FormField>{editing.condition_field && <FormField id="automation-condition-value" label="Sama dengan" as="select" value={editing.condition_value} onChange={e => setEditing({ ...editing, condition_value: e.target.value })}>{(editing.condition_field === 'status' ? statuses.map(s => s.name) : priorities).map(v => <option key={v}>{v}</option>)}</FormField>}</div><FormField id="automation-action" label="Lakukan" as="select" value={editing.action} onChange={e => setEditing({ ...editing, action: e.target.value, action_value: '' })}>{Object.entries(actions).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</FormField>{['set_status', 'set_priority', 'assign', 'notify'].includes(editing.action) ? <FormField id="automation-action-value" label="Nilai aksi" as="select" required value={editing.action_value} onChange={e => setEditing({ ...editing, action_value: e.target.value })}><option value="">Pilih…</option>{editing.action === 'set_status' ? statuses.map(s => <option key={s.id}>{s.name}</option>) : editing.action === 'set_priority' ? priorities.map(v => <option key={v}>{v}</option>) : people.filter(m => editing.action !== 'assign' || m.role === 'Developer').map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</FormField> : <FormField id="automation-action-value" label="Tag" required maxLength={200} value={editing.action_value} onChange={e => setEditing({ ...editing, action_value: e.target.value })} />}<label className="pw-checkbox-line"><input type="checkbox" data-testid="automation-enabled" checked={editing.enabled} onChange={e => setEditing({ ...editing, enabled: e.target.checked })} />Aturan aktif</label><Submit id="automation-save" busy={busy} /></form>}</WorkspaceModal>
  </div>;
};