import React, { useState } from 'react';
import { Target, Pencil, CheckCircle2 } from 'lucide-react';
import { useData } from '../../lib/api';
import { Loading, ErrorState } from '../Common';
import { WorkspaceHead, WorkspaceModal, Action, DeleteAction, FormField, Submit, EmptyWorkspace, TaskPicker, useMutation } from './WorkspaceUI';

export const GoalsPage = ({ p, tasks, manager }) => {
  const base = `/projects/${p.id}/workspace/goals`, goals = useData(base);
  const [editing, setEditing] = useState(null); const { run, busy } = useMutation(goals.reload);
  const payload = g => Object.fromEntries(['name', 'description', 'metric', 'target', 'current', 'unit', 'task_ids', 'due_date'].map(k => [k, k === 'due_date' ? g[k] || null : g[k]]));
  if (goals.loading && !goals.data) return <Loading />; if (goals.error) return <ErrorState error={goals.error} reload={goals.reload} />;
  return <div data-testid="goals-page"><WorkspaceHead id="goals" title="Goals" subtitle={`${goals.data?.filter(g => g.progress >= 100).length || 0} tercapai dari ${goals.data?.length || 0} target`}>{manager && <Action id="create-goal" onClick={() => setEditing({ name: '', description: '', metric: 'tasks', target: 100, current: 0, unit: 'poin', task_ids: [], due_date: '' })}>Goal baru</Action>}</WorkspaceHead>
    {!goals.data?.length && <EmptyWorkspace title="Belum ada goal" id="goals-empty" />}<div className="pw-goal-grid">{goals.data?.map(g => <article key={g.id} className="pw-goal" data-testid={`goal-${g.id}`}><div className="pw-goal-top"><span className={`pw-goal-icon ${g.progress >= 100 ? 'complete' : ''}`}>{g.progress >= 100 ? <CheckCircle2 size={23} /> : <Target size={23} />}</span>{manager && <div className="pw-actions"><button className="pw-icon" data-testid={`edit-goal-${g.id}`} title="Edit goal" onClick={() => setEditing(g)}><Pencil size={15} /></button><DeleteAction id={`delete-goal-${g.id}`} onClick={() => window.confirm('Hapus goal? Task tidak akan dihapus.') && run('delete', `${base}/${g.id}`)} /></div>}</div><h3 data-testid={`goal-name-${g.id}`}>{g.name}</h3><p>{g.description || '—'}</p><div className="pw-goal-numbers" data-testid={`goal-progress-${g.id}`}><b>{g.progress}%</b><span>{g.actual} / {g.total} {g.metric === 'tasks' ? 'task selesai' : g.unit}</span></div><div className="pw-progress"><i style={{ width: `${g.progress}%` }} /></div><footer data-testid={`goal-deadline-${g.id}`}>{g.due_date ? `Target ${g.due_date}` : 'Tanpa batas waktu'}<span>{g.metric === 'tasks' ? 'Progres otomatis' : 'Progres manual'}</span></footer></article>)}</div>
    <WorkspaceModal id="goal-form" open={!!editing} onClose={() => setEditing(null)} title={editing?.id ? 'Edit goal' : 'Goal baru'}>{editing && <form className="pw-form" onSubmit={async e => { e.preventDefault(); if (await run(editing.id ? 'patch' : 'post', base + (editing.id ? '/' + editing.id : ''), payload(editing))) setEditing(null); }}><FormField id="goal-name-input" label="Nama goal" required maxLength={120} value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} /><FormField id="goal-description" label="Deskripsi" as="textarea" maxLength={1000} value={editing.description} onChange={e => setEditing({ ...editing, description: e.target.value })} /><div className="pw-form-grid"><FormField id="goal-metric" label="Ukuran" as="select" value={editing.metric} onChange={e => setEditing({ ...editing, metric: e.target.value })}><option value="tasks">Task selesai</option><option value="number">Target angka</option></FormField><FormField id="goal-due" label="Target tanggal" type="date" value={editing.due_date || ''} onChange={e => setEditing({ ...editing, due_date: e.target.value })} /></div>{editing.metric === 'tasks' ? <TaskPicker id="goal-task-picker" tasks={tasks} value={editing.task_ids} onChange={task_ids => setEditing({ ...editing, task_ids })} /> : <div className="pw-form-grid"><FormField id="goal-target" label="Target" type="number" min="0.01" step="any" required value={editing.target} onChange={e => setEditing({ ...editing, target: Number(e.target.value) })} /><FormField id="goal-current" label="Tercapai" type="number" min="0" step="any" required value={editing.current} onChange={e => setEditing({ ...editing, current: Number(e.target.value) })} /><FormField id="goal-unit" label="Satuan" required maxLength={30} value={editing.unit} onChange={e => setEditing({ ...editing, unit: e.target.value })} /></div>}<Submit id="goal-save" busy={busy} /></form>}</WorkspaceModal>
  </div>;
};