import React from 'react';
import { Flag, ArrowUpRight, CheckCircle2, Clock3, Link2, MessageSquare } from 'lucide-react';
import { Link } from 'react-router-dom';
import { ResponsiveContainer, BarChart, Bar, LineChart, Line, CartesianGrid, XAxis, YAxis, Tooltip, Legend } from 'recharts';
import { useData } from '../../lib/api';
import { Loading, ErrorState } from '../Common';
import { WorkspaceHead } from './WorkspaceUI';

export const ReportsPage = ({ p }) => {
  const report = useData(`/projects/${p.id}/workspace/reports`);
  if (report.loading) return <Loading />; if (report.error) return <ErrorState error={report.error} reload={report.reload} />;
  const d = report.data;
  return <div data-testid="reports-page"><WorkspaceHead id="reports" title="Dashboard Project" subtitle={`${p.name} · ${d.total} task`} /><div className="pw-report-stats">{[[CheckCircle2, 'Selesai', `${d.done}/${d.total}`, 'completed'], [Clock3, 'Terlambat', d.overdue, 'overdue'], [Link2, 'Menunggu prasyarat', d.blocked, 'blocked'], [MessageSquare, 'Komentar tertugas', d.open_comments, 'comments']].map(([Icon, label, value, key]) => <div key={key} data-testid={`report-${key}`}><Icon size={18} /><small>{label}</small><b>{value}</b></div>)}</div>
    <div className="pw-report-grid"><section><h3 data-testid="report-trend-title">Aktivitas 14 hari</h3><div className="pw-chart" data-testid="report-trend-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={d.trend} barGap={2}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#edf0f5" /><XAxis dataKey="date" tickFormatter={v => v.slice(5)} tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis allowDecimals={false} tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip /><Legend /><Bar dataKey="created" name="Dibuat" fill="#99b7f5" radius={[3, 3, 0, 0]} /><Bar dataKey="completed" name="Selesai" fill="#10b981" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></div></section><section><h3 data-testid="report-status-title">Distribusi status</h3><div className="pw-status-bars">{d.statuses.map(s => <div key={s.name} data-testid={`report-status-${s.name}`}><div><span><i style={{ background: s.color }} />{s.name}</span><b>{s.count}</b></div><div className="pw-progress"><i style={{ width: `${d.total ? s.count / d.total * 100 : 0}%`, background: s.color }} /></div></div>)}</div></section></div>
    <div className="pw-report-grid"><section><h3 data-testid="report-time-title">Estimasi & realisasi waktu</h3><div className="pw-time-comparison"><div data-testid="report-estimated"><small>Estimasi total</small><b>{d.estimated}<span> jam</span></b></div><div data-testid="report-actual"><small>Waktu tercatat</small><b>{d.actual}<span> jam</span></b></div><div data-testid="report-time-usage"><small>Terpakai</small><b>{d.estimated ? Math.round(d.actual / d.estimated * 100) : 0}<span>%</span></b></div></div><div className="pw-progress"><i style={{ width: `${Math.min(100, d.estimated ? d.actual / d.estimated * 100 : 0)}%`, background: d.actual > d.estimated ? '#e5484d' : '#2c63e8' }} /></div></section><section><h3 data-testid="report-milestones-title">Milestone</h3><div className="pw-milestone-list">{d.milestones.map(t => <Link key={t.id} data-testid={`report-milestone-${t.id}`} to={`/projects/${p.id}/kanban?task=${t.id}`}><Flag size={17} /><span><b>{t.title}</b><small>{t.status} · {t.due_date || 'Tanpa target tanggal'}</small></span><ArrowUpRight size={15} /></Link>)}{!d.milestones.length && <p className="pw-muted" data-testid="report-milestones-empty">Belum ada milestone.</p>}</div></section></div>
  </div>;
};