import React, { useState } from 'react';
import { Play, CheckCircle2, Pencil, ArrowRight, Timer } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useData } from '../../lib/api';
import { format, addDays } from 'date-fns';
import { Loading, ErrorState } from '../Common';
import { WorkspaceHead, WorkspaceModal, Action, DeleteAction, FormField, Submit, EmptyWorkspace, useMutation } from './WorkspaceUI';
const statusLabels = { planned: 'Direncanakan', active: 'Aktif', completed: 'Selesai' };
export const SprintsPage = ({ p, tasks, manager, reload }) => {
  const base = `/projects/${p.id}/workspace/sprints`, data = useData(base), navigate = useNavigate();
  const [editing, setEditing] = useState(null), [current, setCurrent] = useState('');
  const { run, busy } = useMutation(async () => { await data.reload(); await reload(); });
  if (data.loading && !data.data) return <Loading />; if (data.error) return <ErrorState error={data.error} reload={data.reload} />;
  const sprint = data.data?.find(s => s.id === current) || data.data?.find(s => s.status === 'active') || data.data?.[0];
  const body = s => Object.fromEntries(['name', 'goal', 'start_date', 'end_date', 'status'].map(k => [k, s[k]]));
  const taskRows = sprint ? tasks.filter(t => t.sprint_id === sprint.id) : []; const backlog = tasks.filter(t => !t.sprint_id);
  const move = (tid, sprint_id) => run('post', `/projects/${p.id}/tasks/bulk`, { ids: [tid], sprint_id }, 'Task dipindahkan');
  return <div data-testid="sprints-page"><WorkspaceHead id="sprints" title="Sprint planning" subtitle={`${data.data?.length || 0} sprint · ${backlog.length} task di backlog`}>{manager && <Action id="create-sprint" onClick={() => setEditing({ name: '', goal: '', start_date: format(new Date(), 'yyyy-MM-dd'), end_date: format(addDays(new Date(), 13), 'yyyy-MM-dd'), status: 'planned' })}>Sprint baru</Action>}</WorkspaceHead>
    <div className="pw-sprint-strip">{data.data?.map(s => <button key={s.id} className={s.id === sprint?.id ? 'active' : ''} data-testid={`select-sprint-${s.id}`} onClick={() => setCurrent(s.id)}><span>{s.name}</span><small>{statusLabels[s.status]} · {s.done}/{s.total} task</small></button>)}</div>
    {sprint ? <><div className="pw-sprint-overview" data-testid="sprint-overview"><div><span className={`pw-badge ${sprint.status}`}>{statusLabels[sprint.status]}</span><h3 data-testid="sprint-name">{sprint.name}</h3><p data-testid="sprint-goal">{sprint.goal || '—'}</p><small data-testid="sprint-dates">{sprint.start_date} — {sprint.end_date} · {sprint.estimate} jam estimasi</small></div><div className="pw-actions">{manager && <><button className="pw-icon" data-testid="edit-sprint" title="Edit sprint" onClick={() => setEditing(sprint)}><Pencil size={15} /></button>{sprint.status === 'planned' && <Action id="start-sprint" icon={Play} busy={busy} onClick={() => run('patch', `${base}/${sprint.id}`, { ...body(sprint), status: 'active' }, 'Sprint dimulai')}>Mulai sprint</Action>}{sprint.status === 'active' && <Action id="complete-sprint" icon={CheckCircle2} busy={busy} onClick={() => window.confirm('Tutup sprint ini? Task yang belum selesai tetap tercatat di sprint dan dapat dipindahkan ke backlog.') && run('patch', `${base}/${sprint.id}`, { ...body(sprint), status: 'completed' }, 'Sprint selesai')}>Selesaikan sprint</Action>}<DeleteAction id="delete-sprint" onClick={() => window.confirm('Hapus sprint dan pindahkan task ke backlog?') && run('delete', `${base}/${sprint.id}`)} /></>}</div></div><div className="pw-progress" data-testid="sprint-progress"><i style={{ width: `${sprint.total ? sprint.done / sprint.total * 100 : 0}%` }} /></div></> : <EmptyWorkspace title="Belum ada sprint" id="sprints-empty" />}
    <div className="pw-planning-columns"><section><h3 data-testid="backlog-heading">Backlog <span>{backlog.length}</span></h3>{backlog.map(t => <div className="pw-plan-task" key={t.id} data-testid={`backlog-task-${t.id}`}><button className="pw-text-button" data-testid={`backlog-open-${t.id}`} onClick={() => navigate(`/projects/${p.id}/kanban?task=${t.id}`)}><b>{t.title}</b><small>{t.priority} · {t.estimate_hours || 0} jam</small></button>{manager && sprint && sprint.status !== 'completed' && <button className="pw-icon" data-testid={`add-to-sprint-${t.id}`} title="Masukkan ke sprint" disabled={busy} onClick={() => move(t.id, sprint.id)}><ArrowRight size={17} /></button>}</div>)}{!backlog.length && <p className="pw-muted" data-testid="backlog-empty">Backlog kosong.</p>}</section><section><h3 data-testid="sprint-tasks-heading">Task sprint <span>{taskRows.length}</span></h3>{taskRows.map(t => <div className="pw-plan-task" key={t.id} data-testid={`sprint-task-${t.id}`}><button className="pw-text-button" data-testid={`sprint-open-${t.id}`} onClick={() => navigate(`/projects/${p.id}/kanban?task=${t.id}`)}><b>{t.title}</b><small>{t.status} · {t.estimate_hours || 0} jam</small></button>{manager && <button className="pw-small-button" data-testid={`remove-from-sprint-${t.id}`} disabled={busy} onClick={() => move(t.id, '')}>Ke backlog</button>}</div>)}{!taskRows.length && <p className="pw-muted" data-testid="sprint-tasks-empty">Belum ada task di sprint ini.</p>}</section></div>
    <WorkspaceModal id="sprint-form" open={!!editing} onClose={() => setEditing(null)} title={editing?.id ? 'Edit sprint' : 'Sprint baru'}>{editing && <form className="pw-form" onSubmit={async e => { e.preventDefault(); const r = await run(editing.id ? 'patch' : 'post', base + (editing.id ? '/' + editing.id : ''), body(editing)); if (r) { setCurrent(r.id); setEditing(null); } }}><FormField id="sprint-form-name" label="Nama sprint" required maxLength={120} value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} /><FormField id="sprint-form-goal" label="Tujuan sprint" as="textarea" value={editing.goal} onChange={e => setEditing({ ...editing, goal: e.target.value })} /><div className="pw-form-grid"><FormField id="sprint-form-start" label="Mulai" type="date" required value={editing.start_date} onChange={e => setEditing({ ...editing, start_date: e.target.value })} /><FormField id="sprint-form-end" label="Selesai" type="date" required min={editing.start_date} value={editing.end_date} onChange={e => setEditing({ ...editing, end_date: e.target.value })} /></div><Submit id="sprint-form-save" busy={busy} /></form>}</WorkspaceModal>
  </div>;
};