import React, { useState } from 'react';
import { Layers3, Folder, List, Pencil, Copy, Settings2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { WorkspaceHead, WorkspaceModal, FormField, Submit, Action, DeleteAction, EmptyWorkspace, useMutation } from './WorkspaceUI';

const icons = { space: Layers3, folder: Folder, list: List };
const labels = { space: 'Space', folder: 'Folder', list: 'List' };
export const StructurePage = ({ p, meta, reload, tasks, manager }) => {
  const [editing, setEditing] = useState(null), [field, setField] = useState(null);
  const { run, busy } = useMutation(reload); const base = `/projects/${p.id}/workspace`;
  const navigate = useNavigate();
  const blankNode = (kind = 'space', parent_id = '') => setEditing({ name: '', kind, parent_id, color: '#2c63e8' });
  const saveNode = async e => { e.preventDefault(); const { id, name, kind, parent_id, color } = editing; if (await run(id ? 'patch' : 'post', `${base}/nodes${id ? '/' + id : ''}`, { name, kind, parent_id, color })) setEditing(null); };
  const tree = (parent = '', depth = 0) => meta.nodes.filter(n => n.parent_id === parent).map(n => {
    const Icon = icons[n.kind]; return <React.Fragment key={n.id}><div className="pw-tree-row" style={{ '--depth': depth }} data-testid={`structure-node-${n.id}`}><i style={{ color: n.color }}><Icon size={19} /></i><button data-testid={`structure-open-${n.id}`} className="pw-text-button" onClick={() => navigate(`/projects/${p.id}/kanban?list=${n.id}`)}><b>{n.name}</b><small>{labels[n.kind]}{n.kind === 'list' ? ` · ${tasks.filter(t => t.list_id === n.id).length} task` : ''}</small></button>{manager && <div className="pw-actions">{n.kind !== 'list' && <button className="pw-small-button" data-testid={`structure-child-${n.id}`} onClick={() => blankNode(n.kind === 'space' ? 'folder' : 'list', n.id)}>+ {n.kind === 'space' ? 'Folder / List' : 'List'}</button>}<button className="pw-icon" data-testid={`structure-edit-${n.id}`} title="Edit struktur" onClick={() => setEditing(n)}><Pencil size={14} /></button><DeleteAction id={`structure-delete-${n.id}`} onClick={() => window.confirm(`Hapus ${n.name}?`) && run('delete', `${base}/nodes/${n.id}`)} /></div>}</div>{tree(n.id, depth + 1)}</React.Fragment>;
  });
  return <div data-testid="structure-page"><WorkspaceHead id="structure" title="Struktur ruang kerja" subtitle={`${meta.nodes.filter(n => n.kind === 'space').length} Space · ${meta.nodes.filter(n => n.kind === 'list').length} List`}>{manager && <Action id="create-space" onClick={() => blankNode()}>Space baru</Action>}</WorkspaceHead>
    <div className="pw-structure-tree">{tree()}{!meta.nodes.length && <EmptyWorkspace title="Belum ada Space" id="structure-empty">{manager && <Action id="first-space" onClick={() => blankNode()}>Buat Space</Action>}</EmptyWorkspace>}</div>
    <section className="pw-section"><WorkspaceHead id="fields" title="Custom fields" subtitle={`${meta.fields.length} field project`}>{manager && <Action id="create-field" secondary icon={Settings2} onClick={() => setField({ name: '', kind: 'text', options: '', visibility: 'Internal' })}>Tambah field</Action>}</WorkspaceHead><div className="pw-config-list">{meta.fields.map(f => <div className="pw-config-row" key={f.id} data-testid={`field-definition-${f.id}`}><span><b>{f.name}</b><small>{f.kind} · {f.visibility === 'Client' ? 'Tim & klien' : 'Internal'}{f.options?.length ? ` · ${f.options.join(', ')}` : ''}</small></span>{manager && <DeleteAction id={`field-delete-${f.id}`} onClick={() => window.confirm('Hapus field dan nilainya dari semua task?') && run('delete', `${base}/fields/${f.id}`)} />}</div>)}{!meta.fields.length && <p className="pw-muted" data-testid="fields-empty">Belum ada custom field.</p>}</div></section>
    <section className="pw-section"><WorkspaceHead id="templates" title="Template tugas" subtitle={`${meta.templates.length} template tersimpan`} /><div className="pw-item-grid">{meta.templates.map(t => <article className="pw-item" key={t.id} data-testid={`template-${t.id}`}><Copy size={20} /><b>{t.name}</b><small>{t.created_by}</small>{manager && <div className="pw-actions"><Action id={`template-apply-${t.id}`} secondary busy={busy} onClick={async () => { const result = await run('post', `${base}/templates/${t.id}/apply`, { list_id: '' }, 'Task dari template dibuat'); if (result) navigate(`/projects/${p.id}/kanban?task=${result.id}`); }}>Buat task</Action><DeleteAction id={`template-delete-${t.id}`} onClick={() => window.confirm('Hapus template?') && run('delete', `${base}/templates/${t.id}`)} /></div>}</article>)}{!meta.templates.length && <p className="pw-muted" data-testid="templates-empty">Belum ada template tersimpan.</p>}</div></section>
    <WorkspaceModal id="node-form" open={!!editing} onClose={() => setEditing(null)} title={editing?.id ? 'Edit struktur' : 'Struktur baru'}>{editing && <form onSubmit={saveNode} className="pw-form"><FormField id="node-name" label="Nama" required maxLength={80} autoFocus value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} /><FormField id="node-kind" label="Jenis" as="select" disabled={!!editing.id} value={editing.kind} onChange={e => setEditing({ ...editing, kind: e.target.value, parent_id: '' })}>{Object.keys(labels).map(k => <option value={k} key={k}>{labels[k]}</option>)}</FormField>{editing.kind !== 'space' && <FormField id="node-parent" label="Induk" as="select" required value={editing.parent_id} onChange={e => setEditing({ ...editing, parent_id: e.target.value })}><option value="">Pilih induk</option>{meta.nodes.filter(n => editing.kind === 'folder' ? n.kind === 'space' : ['space', 'folder'].includes(n.kind)).map(n => <option key={n.id} value={n.id}>{labels[n.kind]} · {n.name}</option>)}</FormField>}<FormField id="node-color" label="Warna" type="color" value={editing.color} onChange={e => setEditing({ ...editing, color: e.target.value })} /><div className="pw-form-actions"><Submit id="node-save" busy={busy} /></div></form>}</WorkspaceModal>
    <WorkspaceModal id="field-form" open={!!field} onClose={() => setField(null)} title="Custom field baru">{field && <form className="pw-form" onSubmit={async e => { e.preventDefault(); if (await run('post', `${base}/fields`, { ...field, options: field.options.split(',').map(s => s.trim()).filter(Boolean) })) setField(null); }}><FormField id="custom-field-name" label="Nama field" required maxLength={60} value={field.name} onChange={e => setField({ ...field, name: e.target.value })} /><FormField id="custom-field-kind" label="Tipe" as="select" value={field.kind} onChange={e => setField({ ...field, kind: e.target.value })}>{[['text', 'Teks'], ['number', 'Angka'], ['date', 'Tanggal'], ['dropdown', 'Pilihan'], ['checkbox', 'Checkbox']].map(([k, n]) => <option key={k} value={k}>{n}</option>)}</FormField>{field.kind === 'dropdown' && <FormField id="custom-field-options" label="Pilihan, pisahkan koma" required value={field.options} onChange={e => setField({ ...field, options: e.target.value })} />}<FormField id="custom-field-visibility" label="Akses" as="select" value={field.visibility} onChange={e => setField({ ...field, visibility: e.target.value })}><option value="Internal">Tim internal</option><option value="Client">Tim dan klien</option></FormField><div className="pw-form-actions"><Submit id="custom-field-save" busy={busy} /></div></form>}</WorkspaceModal>
  </div>;
};