import React, { useState } from 'react';
import { Flag, Copy, CalendarClock, Bell, X } from 'lucide-react';
import { useData, api, errorText } from '../../lib/api';
import { toast } from 'sonner';
import { WorkspaceModal, FormField, Submit, useMutation } from './WorkspaceUI';

const localDate = value => { if (!value) return ''; const d = new Date(value); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16); };
export const TaskExtras = ({ task, project, manager, internal, patch }) => {
  const base = `/projects/${project.id}/workspace`; const meta = useData(`${base}/meta`);
  const schedule = useData(internal ? `${base}/tasks/${task.id}/schedule` : null);
  const [template, setTemplate] = useState(null), [repeat, setRepeat] = useState(null);
  const { run, busy } = useMutation(schedule.reload);
  const fields = meta.data?.fields || [];
  return <section className="ck-section pw-task-extras" data-testid="task-extras"><h4 data-testid="task-planning-heading">Perencanaan</h4><div className="ck-props">
    <label className="ck-prop"><small>List</small><select data-testid="task-list-select" className="ck-inline" disabled={!manager} value={task.list_id || ''} onChange={e => patch({ list_id: e.target.value })}><option value="">Tanpa List</option>{(meta.data?.nodes || []).filter(n => n.kind === 'list').map(n => <option key={n.id} value={n.id}>{n.name}</option>)}</select></label>
    <label className="ck-prop"><small>Sprint</small><select data-testid="task-sprint-select" className="ck-inline" disabled={!manager} value={task.sprint_id || ''} onChange={e => patch({ sprint_id: e.target.value })}><option value="">Backlog</option>{(meta.data?.sprints || []).filter(s => s.status !== 'completed' || s.id === task.sprint_id).map(s => <option key={s.id} value={s.id} disabled={s.status === 'completed'}>{s.name}</option>)}</select></label>
    <label className="ck-prop"><small>Milestone</small><span className="pw-checkbox-line"><input type="checkbox" data-testid="task-milestone-toggle" disabled={!manager} checked={!!task.milestone} onChange={e => patch({ milestone: e.target.checked }, 'Milestone diperbarui')} /><Flag size={14} /> Milestone project</span></label>
    {internal && <label className="ck-prop"><small>Pengingat</small><div className="pw-inline"><input type="datetime-local" data-testid="task-reminder" className="ck-inline" disabled={!manager} value={localDate(task.reminder_at)} onChange={e => patch({ reminder_at: e.target.value ? new Date(e.target.value).toISOString() : null }, 'Pengingat disimpan')} />{task.reminder_sent_at && <small className="pw-success" data-testid="reminder-sent">Terkirim</small>}</div></label>}
  </div>
  {!!fields.length && <div className="pw-custom-values"><h4 data-testid="custom-values-heading">Custom fields</h4>{fields.map(f => { const value = task.custom_fields?.[f.id]; const update = v => patch({ custom_fields: { ...task.custom_fields, [f.id]: v } }, 'Field disimpan'); return <label className="pw-field" key={f.id}><span>{f.name}</span>{f.kind === 'dropdown' ? <select data-testid={`task-field-${f.id}`} disabled={!manager} value={value || ''} onChange={e => update(e.target.value)}><option value="">Belum diisi</option>{f.options.map(o => <option key={o}>{o}</option>)}</select> : f.kind === 'checkbox' ? <input type="checkbox" data-testid={`task-field-${f.id}`} disabled={!manager} checked={!!value} onChange={e => update(e.target.checked)} /> : <input key={`${f.id}-${value}`} type={f.kind === 'text' ? 'text' : f.kind} data-testid={`task-field-${f.id}`} disabled={!manager} defaultValue={value ?? ''} onBlur={e => { const v = e.target.value === '' ? null : f.kind === 'number' ? Number(e.target.value) : e.target.value; if (v !== value) update(v); }} />}</label>; })}</div>}
  {manager && <div className="pw-task-tools"><button type="button" className="pw-small-button" data-testid="save-task-template" onClick={() => setTemplate(task.title)}><Copy size={14} /> Simpan template</button><button type="button" className={`pw-small-button ${schedule.data?.enabled ? 'active' : ''}`} data-testid="task-repeat-open" onClick={() => setRepeat({ frequency: schedule.data?.frequency || 'weekly', next_run: localDate(schedule.data?.next_run || new Date(Date.now() + 86400000).toISOString()), end_at: localDate(schedule.data?.end_at), enabled: schedule.data?.enabled ?? true })}><CalendarClock size={14} />{schedule.data ? `Berulang · ${schedule.data.enabled ? 'Aktif' : 'Jeda'}` : 'Ulangi task'}</button>{schedule.data && <button type="button" className="pw-icon danger" data-testid="task-repeat-delete" title="Hentikan pengulangan" onClick={() => window.confirm('Hentikan pengulangan?') && run('delete', `${base}/tasks/${task.id}/schedule`)}><X size={14} /></button>}</div>}
  {schedule.data?.next_run && <small className="pw-muted" data-testid="task-next-repeat">Berikutnya: {new Date(schedule.data.next_run).toLocaleString('id-ID')}</small>}
  <WorkspaceModal id="template-save" open={template !== null} onClose={() => setTemplate(null)} title="Simpan template tugas"><form className="pw-form" onSubmit={async e => { e.preventDefault(); if (await run('post', `${base}/tasks/${task.id}/template`, { name: template }, 'Template disimpan')) setTemplate(null); }}><FormField id="template-name" label="Nama template" required maxLength={120} value={template || ''} onChange={e => setTemplate(e.target.value)} /><Submit id="template-save-submit" busy={busy} /></form></WorkspaceModal>
  <WorkspaceModal id="repeat-form" open={!!repeat} onClose={() => setRepeat(null)} title="Pengulangan tugas">{repeat && <form className="pw-form" onSubmit={async e => { e.preventDefault(); if (await run('post', `${base}/tasks/${task.id}/schedule`, { ...repeat, next_run: new Date(repeat.next_run).toISOString(), end_at: repeat.end_at ? new Date(repeat.end_at).toISOString() : null }, 'Jadwal pengulangan disimpan')) setRepeat(null); }}><FormField id="repeat-frequency" label="Frekuensi" as="select" value={repeat.frequency} onChange={e => setRepeat({ ...repeat, frequency: e.target.value })}><option value="daily">Harian</option><option value="weekly">Mingguan</option><option value="monthly">Bulanan</option></FormField><FormField id="repeat-next" label="Jadwal pertama (waktu lokal)" type="datetime-local" required value={repeat.next_run} onChange={e => setRepeat({ ...repeat, next_run: e.target.value })} /><FormField id="repeat-end" label="Berakhir (opsional)" type="datetime-local" value={repeat.end_at} onChange={e => setRepeat({ ...repeat, end_at: e.target.value })} /><label className="pw-checkbox-line"><input data-testid="repeat-enabled" type="checkbox" checked={repeat.enabled} onChange={e => setRepeat({ ...repeat, enabled: e.target.checked })} />Pengulangan aktif</label><Submit id="repeat-save" busy={busy} /></form>}</WorkspaceModal>
  </section>;
};